CREATE TABLE cards (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50),
    image VARCHAR(100),
    description VARCHAR(500),
    effect VARCHAR(250),
    rarity VARCHAR(10)
);
INSERT INTO cards(name,image,description,effect,rarity) VALUES 
('Susi','common_1',NULL,NULL,'common'),
('Franz','common_2',NULL,NULL,'common'),
('Herbert','common_3',NULL,NULL,'common'),
('Darcy','common_4',NULL,NULL,'common'),
('Gustav','common_5',NULL,NULL,'common'),
('Barbara','common_6',NULL,NULL,'common'),
('Fred','common_7',NULL,NULL,'common'),
('Bernd','common_8',NULL,NULL,'common'),
('Marcy','common_9',NULL,NULL,'common'),
('Finn','common_10',NULL,NULL,'common'),
('Pius','common_11',NULL,NULL,'common'),
('Stella','common_12',NULL,NULL,'common'),
('Jake','common_13',NULL,NULL,'common'),
('Silas','common_14',NULL,NULL,'common'),
('Bodo','common_15',NULL,NULL,'common'),
('Silko','common_16',NULL,NULL,'common'),
('Otto','common_17',NULL,NULL,'common'),
('Ophelia','common_18',NULL,NULL,'common'),
('Kaspar','common_19',NULL,NULL,'common'),
('Caitlyn','common_20',NULL,NULL,'common'),
('Oliver','common_21',NULL,NULL,'common'),
('Hedda','common_22',NULL,NULL,'common'),
('Bella','common_23',NULL,NULL,'common'),
('Drago','common_24',NULL,NULL,'common'),
('Guiseppe','common_25',NULL,NULL,'common'),
('Brian','common_26',NULL,NULL,'common'),
('Peter','uncommon_1',NULL,NULL,'uncommon'),
('Bob','uncommon_2',NULL,NULL,'uncommon'),
('Cameo','uncommon_3',NULL,NULL,'uncommon'),
('Till','uncommon_4',NULL,NULL,'uncommon'),
('Mattis','uncommon_5',NULL,NULL,'uncommon'),
('Christina','uncommon_6',NULL,NULL,'uncommon'),
('Erik','uncommon_7',NULL,NULL,'uncommon'),
('Jesper','uncommon_8',NULL,NULL,'uncommon'),
('Rica','uncommon_9',NULL,NULL,'uncommon'),
('Tom','uncommon_10',NULL,NULL,'uncommon'),
('Celina','uncommon_11',NULL,NULL,'uncommon'),
('Lina','uncommon_12',NULL,NULL,'uncommon'),
('Ferdinand','uncommon_13',NULL,NULL,'uncommon'),
('Anastasia','uncommon_14',NULL,NULL,'uncommon'),
('Nick','uncommon_15',NULL,NULL,'uncommon'),
('Parvis','rare_1',NULL,NULL,'rare'),
('Lola,Lilly & Louise','rare_2',NULL,NULL,'rare'),
('Jim & Pia','rare_3',NULL,NULL,'rare'),
('Kurt & Karl','rare_4',NULL,NULL,'rare'),
('Till & Mattis','rare_5',NULL,NULL,'rare'),
('Bruno & Egon','rare_6',NULL,NULL,'rare'),
('Jacques & Eugene','rare_7',NULL,NULL,'rare'),
('Cleo, Clara & Charlotte','rare_8',NULL,NULL,'rare'),
('Wasteland','rare_9',NULL,NULL,'rare');